from tkinter import *
root=Tk()
root.title("subhadeep chell")
root.geometry("664x434")
root.minsize(200,100)
root.maxsize(1200,988)
x=Label(text="my name is subhadeep chell")
x.pack()
x=Label(text="i read in class XII")
x.pack()
x=Label(text="bhojpuri classics")
x.pack()
root.mainloop()
